### ISSUE TITLE
I can't access route information within the Form Request

### ISSUE THREAD

**Issue by jorgemudry** [ssi-anik/form-request#3]
If I need to access route information (the controller being used or the route's parameters) I can't do it within the form request file or even in the controller where it was injected.

Here's an example of what I mean:

Giving the route `$router->get('accounts/{account}', ['uses' => 'Controller@show']);` if I use the regular Request class in my controller's method I can do something like:

```php
    public function show(Request $request)
    {
        dd($request->route());
    }
```

Which will return an array containing the route's information (for the URL `http://127.0.0.1:8000/accounts/1`):

```php
        [
            0 => 1,
            1 => [
              "uses" => "App\Http\Controllers\Controller@show"
            ],
            2 => [
              "account" => "1"
            ]
        ]
```

But, if I use the form request instead, it returns `null`.

Let me know if you need more information.

Thanks!

**Comment by ssi-anik** [comment]
What's your lumen version and the package version?

**Comment by ssi-anik** [comment]
Found the problem.
Change this with the following for now in your local environment if you don't have to push in the code in test/production environment.

https://github.com/ssi-anik/form-request/blob/f11e35c94d05bfe0336851f2939cf7318d78f090/src/FormRequestServiceProvider.php#L21-L27

```php
protected function initializeRequest (FormRequest $form, $app) {
    $request = FormRequest::createFrom($app['request'], $form);
}
```

Allow me a day, it'd be fixed by today or tomorrow if alive.

**Comment by ssi-anik** [comment]
Edited the snippet. removed the `$form->setUserResolver($current->getUserResolver());` as it's already been done in the `::createFrom` method.

**Comment by jorgemudry** [comment]
Will do! thanks!

**Comment by jorgemudry** [comment]
Ok, now I can see the array if I do `dd($request->route());` but if I try to access the value of the parameter I set it fails:

<img width="1036" alt="Screen Shot 2021-04-09 at 23 52 37" src="https://user-images.githubusercontent.com/1508989/114256301-ca196600-998e-11eb-97d0-44ca2aab4249.png">

**Comment by ssi-anik** [comment]
The problem lies in the Laravel end. Because, when you call `$request->route()`, you'll get an array in return. And thus you can't `->parameter()` on an array.
As route resolver, in Laravel, they use `\Illuminate\Routing\Route`. whereas they use an array.

[Lumen] Backtracking the following variable you'll see it's an array in the top where it's declared.
https://github.com/laravel/lumen-framework/blob/e7e24ec0692d6dea859ece633f444bb0b977638d/src/Application.php#L538-L542

[Laravel] 
https://github.com/illuminate/routing/blob/8f479cf463af995d72035a575cfc70c0022e0e74/Router.php#L663-L674

You can access it like `$request->route()['account'] ?? 'not available'`. Not sure if it may help. https://medium.com/@sirajul.anik/laravel-lumen-manipulating-route-controller-parameters-5f3cbcb521b4

**Comment by jorgemudry** [comment]
Yes, I could use that solution in this case. I just pointed out the error because using the regular class Request I do get the value for that parameter.

What I'm saying is, using the form request for some reason it shows the array but tries to call the `->parameter()` method on that array but with the regular Request class, it shows the array as well, but when I try to access the parameter somehow it works

**Comment by ssi-anik** [comment]
okay. will consider this one as well when I'll work. Thanks.

**Comment by ssi-anik** [comment]
I was unaware of the `Laravel\Lumen\Http\Request` class. You're importing that class instead of the base `Illuminate\Http\Request` class. That's why you're getting the value. https://github.com/laravel/lumen-framework/issues/484#issuecomment-683260582

Thanks for pointing it out. I'd make the necessary changes now and inform here.

**Comment by jorgemudry** [comment]
Based on your comment I checked the code and I'm importing the `Illuminate\Http\Request` class BUT it is just an alias to `Laravel\Lumen\Http\Request` so when I use `Illuminate\Http\Request` lumen is resolving `Laravel\Lumen\Http\Request`.

```php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Laravel\Lumen\Routing\Controller as BaseController;

class Controller extends BaseController
{
    public function show(Request $request)
    {
        dd($request);
    }
}
```

results in:

<img width="373" alt="Screen Shot 2021-04-10 at 13 32 57" src="https://user-images.githubusercontent.com/1508989/114277396-63816000-9a01-11eb-8d4d-cb278833c6b5.png">

and the same happens with your code:

```php
<?php namespace Anik\Form;

use Illuminate\Support\ServiceProvider;

class FormRequestServiceProvider extends ServiceProvider
{
    public function register () {
    }

    public function boot () {
        $this->app->resolving(FormRequest::class, function ($request, $app) {
            $this->initializeRequest($request, $app);
        });

        $this->app->afterResolving(FormRequest::class, function ($form) {
            $form->validate();
        });
    }

    protected function initializeRequest (FormRequest $form, $app) {
        dd($app['request']);
        $request = FormRequest::createFrom($app['request'], $form);
    }
}
```

results in:

<img width="390" alt="Screen Shot 2021-04-10 at 13 35 06" src="https://user-images.githubusercontent.com/1508989/114277459-a93e2880-9a01-11eb-9ce9-e74a3bf60abc.png">

So we're always using `Laravel\Lumen\Http\Request`

**Comment by jorgemudry** [comment]
Ok, I think I made it work.

If you extend the `FormRequest` class from `Laravel\Lumen\Http\Reques` it does not return an error when I try to access a specific key from the `route` method (or if I try to access the value directly like `$this->account` inside of a form request class):

```php
<?php namespace Anik\Form;

use Illuminate\Validation\UnauthorizedException;
use Laravel\Lumen\Http\Request;

abstract class FormRequest extends Request
{
    public function validate () {
        if (false === $this->authorize()) {
            throw new UnauthorizedException();
        }

        $validator = app('validator')->make($this->all(), $this->rules(), $this->messages());

        if ($validator->fails()) {
            throw new ValidationException($validator->errors());
        }
    }

    protected function authorize () {
        return true;
    }

    abstract protected function rules ();

    protected function messages () {
        return [];
    }
}
```

**Comment by ssi-anik** [comment]
Yes, using that class on the new branch. Can you use this? https://packagist.org/packages/anik/form-request#v4.x-dev
I will put a tag tomorrow hopefully.

**Comment by jorgemudry** [comment]
I will! Thanks a lot! 😄

**Comment by ssi-anik** [comment]
Try out the `^v4.0`
